[11.0] [MIG] Migrate donation_sale
OCA/donation pull request #47
Opened 2018-10-15 06:30 UTC by nikul-serpentcs

Donation Sale
=============
To get some real features, you should install the *donation* or the *donation_sale* module.

2018-10-15 12:10 UTC, nikul-serpentcs commented
@JayVora-SerpentCS @pedrobaeza @tafaRU @alexis-via  Could you please review it?

2018-10-22 14:33 UTC, JayVora-SerpentCS requested changes

2018-10-22 14:33 UTC, JayVora-SerpentCS commented on donation_sale/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Can you use Readme generator plz?
https://github.com/OCA/maintainer-tools/blob/master/tools/gen_addon_readme.py

2018-10-28 08:34 UTC, alexis-via approved these changes

2018-10-28 08:35 UTC, merged

2018-10-28 08:35 UTC, alexis-via commented
I made a rapid review, that's fine for me. There has been several improvements in the 10.0 branch in the meantime, which would be great to up-port, but this can be done in a later PR, I don't want to post-pone this for an up-port.